### ISSUE TITLE
PSX (PS1) games?

### ISSUE THREAD

**Issue by rand92000** [LiEnby/chovy-sign#10]
I know it's very similar file formats for vita and in general so is there any way to make it work?
Or could you please support them?
Many thanks for reply in advance :)

**Comment by KuromeSan** [comment]
I was working on it current master commit even has a menu for it someone got it to work on cbps forums but it uses some weird compression on the iso ..

**Comment by BeemerDream** [comment]
Any update on this? 
Would love to see if you could play games that isn´t on PS Store like Gran Turismo for ex. or other great games.
Thanks for reply in advance.

**Comment by KuromeSan** [comment]
nope, i kinda stopped looking into it though, maybe if i feel like working on it again,
part of the reason is because 3.73 is hacked there isnt *that much* of a reason to look into it,
besides maybe for pocketstation

**Comment by BeemerDream** [comment]
Ok, but it would be great to play them natively, just like with the PSP games (chovy-sign) and not with Adrenaline. 
I tried to look into it, but i'm not so experienced. 
I hope you feel like working on it sometime. 
Thx for your reply.

**Comment by YaketyJoe** [comment]
Yea, the problem with 3.73, is that it needs to be downgraded and have custom firmware, to use Adrenaline. I’d love to stay on latest firmware and use Chovy-Sign to play PS1 games. Hopefully someday. :-)

**Comment by pkdenn** [comment]
Playing them natively would be a dream, works great with PSP games, specially those that were delisted. Chovy-sign for PSX games could be brilliant!

**Comment by alfredox123** [comment]
would be nice to play pocket fighter natively :c

**Comment by LakiBR** [comment]
In fact PS1 support would be amazing. Since I have known about chovy-sign never used Adrenaline anymore. Chovy-sign is way better than Adrenaline, in many factors.
