### ISSUE TITLE
PSVIMG-EXTRACT.EXE FAILED!

### ISSUE THREAD

**Issue by Cerberus-99** [LiEnby/chovy-sign#12]
![Sin título](https://user-images.githubusercontent.com/81010978/111864347-f27cea00-8925-11eb-8326-23b2b60ca9a2.png)
Hello. I have used this program before but now im getting this error while tryng to read the Locoroco file.

**Comment by KuromeSan** [comment]
your using an old version thou ;-;

**Comment by KuromeSan** [comment]
but it looks like the file your using is some leftover files from an incomplete copy from the PSVita -> PC ..

**Comment by Cerberus-99** [comment]
I'musing beta 3. Tried deleting the game and re downloading it. Still the same. Triend beta 1 and 2 same. Tried 3 computers still same.

**Comment by KuromeSan** [comment]
well the cma backup file your using is called _tmp which is what QCMA does with games its copying over but has npt finished copying

also whos that girl and does she die?
