### ISSUE TITLE
Use Content Manager (Package to PSVIMG)

### ISSUE THREAD

**Issue by LakiBR** [LiEnby/chovy-sign#22]
I found that option in settings, and tried to untickle it, to transfer the files (EBOOT.PBP and SCE) using my PC to SD2Vita on PSTV (way faster). Forced the update database, and the bubble succesfully was installed, but the game starts and come back to the Live Area.

Since, I'm using the licenses correct, it should be working, right?

Thank you so much for your full support.

**Comment by LakiBR** [comment]
Edit: It works. I was mismatching some configs.

**Comment by lautiab** [comment]
@LakiBR Mind pointing out what you did, I'm facing the same issue here and I could not sort it out yet.

**Comment by LakiBR** [comment]
I don't remember quite well what was the problem, but I remember I was selecting the improper license on the software itself. When I checked everything again, the process works properly.

PS: You have to keep the license of the "original" game you used too.

**Comment by LiEnby** [comment]
> PS: You have to keep the license of the "original" game you used too.

this is basically the "trick" chovy-sign uses, we don't have the keys to sign licenses, but we do have the keys to sign PBP's for some reason, so there is nothing stopping you just signing a PBP with the same encryption key for a game you *do* own legitimately,
