### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by Plaxaris92** [LiEnby/chovy-sign#30]
Hi, is there a way to change or remove the splash screen in games?

**Comment by Plaxaris92** [comment]
Fixed using Chovy Sign Mod

**Comment by lance8765** [comment]
> Fixed using Chovy Sign Mod

Huh... where's is this Chovy Sign Mod?

**Comment by LiEnby** [comment]
its here;
https://github.com/reinforchu/chovy-sign-mod/

it looks like they just changed the startdatpops and startdatpsp PNG files in the source; to the PSP startup and PS1 startup screens. 
they can be anything, i just use the "Chovy-Sign" message in MINIs font. see this  https://github.com/reinforchu/chovy-sign-mod/commit/eaf82ff6b5ce925dc1a2514bb3f7127285cb4a2b

**Comment by lance8765** [comment]
> its here; https://github.com/reinforchu/chovy-sign-mod/
> 
> it looks like they just changed the startdatpops and startdatpsp PNG files in the source; to the PSP startup and PS1 startup screens. they can be anything, i just use the "Chovy-Sign" message in MINIs font. see this [reinforchu@a382400](https://github.com/reinforchu/chovy-sign-mod/commit/a38240068be46d987211228204bd5429e3fd8ebf)

Much appreciated.

**Comment by lowendgamer** [comment]
How to change the boot screen to the default psp warning image?
